# Generated by Django 5.1.3 on 2025-02-07 17:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.AddField(
            model_name='metatag',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='metatag',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metatag',
            name='title_page',
            field=models.TextField(default=django.utils.timezone.now, max_length=80, verbose_name='Заголовок страницы (максимум 80 символов)'),
            preserve_default=False,
        ),
    ]
